<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.messaging.simp.annotation.support.SubscriptionMethodReturnValueHandlerTests" tests="4" skipped="0" failures="0" errors="0" timestamp="2019-12-21T15:04:58" hostname="yunlongdeMacBook-Pro.local" time="0.103">
  <properties/>
  <testcase name="testJsonView()" classname="org.springframework.messaging.simp.annotation.support.SubscriptionMethodReturnValueHandlerTests" time="0.063"/>
  <testcase name="testHeadersPassedToMessagingTemplate()" classname="org.springframework.messaging.simp.annotation.support.SubscriptionMethodReturnValueHandlerTests" time="0.034"/>
  <testcase name="testMessageSentToChannel()" classname="org.springframework.messaging.simp.annotation.support.SubscriptionMethodReturnValueHandlerTests" time="0.004"/>
  <testcase name="supportsReturnType()" classname="org.springframework.messaging.simp.annotation.support.SubscriptionMethodReturnValueHandlerTests" time="0.001"/>
  <system-out><![CDATA[23:04:58.959 [MessageBroker-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
java.lang.NullPointerException: null
	at org.springframework.messaging.simp.user.MultiServerUserRegistry$UserRegistrySnapshot.<init>(MultiServerUserRegistry.java:212) ~[main/:?]
	at org.springframework.messaging.simp.user.MultiServerUserRegistry.getLocalRegistryDto(MultiServerUserRegistry.java:164) ~[main/:?]
	at org.springframework.messaging.simp.user.UserRegistryMessageHandler$UserRegistryTask.run(UserRegistryMessageHandler.java:141) ~[main/:?]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.3.BUILD-SNAPSHOT.jar:5.2.3.BUILD-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
